import ScrollToTop from "react-scroll-to-top";
import React from 'react';
const Template = (props) => {

    return (
        <div>
            <header>
                <title>SF Technologies - Software Development | Digital Solution | IT Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="apple-touch-icon" sizes="180x180" href="/website/2022/11/assets/apple-touch-icon.d047f6.png" />
                <link rel="icon" type="image/png" sizes="64x64" href="./images/Frame 14.svg"></link>
                <link rel="icon" type="image/png" sizes="32x32" href="/website/2023/06/assets/favicon-32x32.164049.png"></link>
            </header>
            <div >
                {props.children}
                <ScrollToTop smooth />
            </div>
        </div>

    )
}

export default Template